### ISSUE TITLE
[Feature request] Add parameter to vanilla-specs to support locust --stop-timeout

### ISSUE THREAD

**Issue by aleks-vodolazko** [AbdelrhmanHamouda/intensive-brew#49]
**Is your feature request related to a problem? Please describe.**
Sometimes some conditions/operations should be executed before launching the on_stop method when timeout is reached.
_Example_:
```
        with client.request(your_args, catch_response=True) as resp:
            if resp.status_code == 200:
                self.foo += 1    // This action will be ignored if run-time timeout is fired before the response is received. 
                resp.success()
            else:
                resp.failure()
```

**Describe the solution you'd like**
This type of issue can be handled by adding a special timeout to finish the current task execution. 
Locust has a special flag to set -s STOP_TIMEOUT, --stop-timeout. It could be 0 by default, but it would be great to have it configurable.

**Describe alternatives you've considered**
If we can have an additional field in .yaml file such as "customParameters" or "customFlags" or "additionalFlags" that will be added at the end of the locust launching command - it would provide full support of all locust flags.

**Additional context**
https://github.com/locustio/locust/pull/1099

**Comment by AbdelrhmanHamouda** [comment]
This is a valid use case and would be a welcomed addition to the project
